import type { Metadata } from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import Navbar from "./component/navbar";
import Footer from "./component/footer";

const geistSans = Inter({
  subsets: ["latin"],
  variable: "--font-geist-Sans",
  weight: ["400", "500"],
  style:["normal","italic"]
});
const geistMono = Inter({
  subsets: ["latin"],
  variable: "--font-geist-Mano",
  weight: ["400","500"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
